import React from "react";
import { ColorTheme } from "../../../themes/colors";
import { getLegalStyles } from "../../../themes/styles/legal";

interface TermsOfUseProps {
    theme: ColorTheme;
    onBack: () => void;
}

const TermsOfUse: React.FC<TermsOfUseProps> = ({ theme, onBack }) => {
    const styles = getLegalStyles(theme);

    return (
        <div style={styles.container}>
            <div style={styles.content}>
                <div style={styles.header}>
                    <button
                        style={styles.backButton}
                        onClick={onBack}
                        onMouseEnter={(e) => {
                            e.currentTarget.style.transform = "translateY(-2px)";
                            e.currentTarget.style.boxShadow = "0 6px 16px rgba(0, 0, 0, 0.2)";
                        }}
                        onMouseLeave={(e) => {
                            e.currentTarget.style.transform = "translateY(0)";
                            e.currentTarget.style.boxShadow = "0 4px 12px rgba(0, 0, 0, 0.15)";
                        }}
                    >
                        ← Back to Cook AI
                    </button>
                    <h1 style={styles.title}>
                        <span style={styles.gradientText}>Terms of Use</span>
                    </h1>
                    <p style={styles.lastUpdated}>Last Updated: January 2025</p>
                </div>

                <div style={styles.section}>
                    <p style={styles.paragraph}>
                        Welcome to <span style={styles.highlight}>Cook AI</span>! By accessing or using our AI-powered recipe generation application, you agree to be bound by these Terms of Use. Please read them carefully before using our service.
                    </p>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>1. Acceptance of Terms</h2>
                    <p style={styles.paragraph}>
                        By using Cook AI, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use and our Privacy Policy. If you do not agree with any part of these terms, you should not use our service.
                    </p>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>2. Description of Service</h2>
                    <p style={styles.paragraph}>
                        Cook AI is an AI-powered application that generates personalized recipes based on ingredients you provide. Our service includes:
                    </p>
                    <ul style={styles.list}>
                        <li style={styles.listItem}>AI-generated recipe suggestions based on your input ingredients</li>
                        <li style={styles.listItem}>Cooking instructions and preparation steps</li>
                        <li style={styles.listItem}>Nutritional information estimates</li>
                        <li style={styles.listItem}>Recipe customization options</li>
                        <li style={styles.listItem}>Ingredient substitution recommendations</li>
                    </ul>
                </div>

                <div style={styles.warningBox}>
                    <div style={styles.warningTitle}>
                        ⚠️ Important Disclaimer
                    </div>
                    <p style={styles.warningText}>
                        Cook AI provides recipe suggestions generated by artificial intelligence. While we strive for accuracy, we cannot guarantee that all recipes are safe, accurate, or suitable for your dietary needs. Always use your judgment and consult healthcare professionals for dietary advice.
                    </p>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>3. User Responsibilities</h2>
                    <p style={styles.paragraph}>
                        When using Cook AI, you agree to:
                    </p>
                    <ul style={styles.list}>
                        <li style={styles.listItem}>Provide accurate ingredient information</li>
                        <li style={styles.listItem}>Use the service for lawful purposes only</li>
                        <li style={styles.listItem}>Not attempt to manipulate or abuse the AI system</li>
                        <li style={styles.listItem}>Verify recipe safety and suitability before cooking</li>
                        <li style={styles.listItem}>Check for food allergies and dietary restrictions</li>
                        <li style={styles.listItem}>Use proper food safety practices when cooking</li>
                    </ul>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>4. AI-Generated Content</h2>
                    <p style={styles.paragraph}>
                        All recipes and cooking instructions are generated by artificial intelligence technology. While our AI is trained on extensive culinary data, please note:
                    </p>
                    <ul style={styles.list}>
                        <li style={styles.listItem}>AI-generated recipes may occasionally contain errors or unusual combinations</li>
                        <li style={styles.listItem}>Cooking times and temperatures should be verified for safety</li>
                        <li style={styles.listItem}>Nutritional information is estimated and may not be completely accurate</li>
                        <li style={styles.listItem}>Always check ingredient compatibility and food safety guidelines</li>
                    </ul>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>5. Food Safety and Allergies</h2>
                    <p style={styles.paragraph}>
                        <strong>You are solely responsible for:</strong>
                    </p>
                    <ul style={styles.list}>
                        <li style={styles.listItem}>Checking all ingredients for allergens before cooking</li>
                        <li style={styles.listItem}>Ensuring food is cooked to safe temperatures</li>
                        <li style={styles.listItem}>Following proper food handling and storage procedures</li>
                        <li style={styles.listItem}>Consulting medical professionals about dietary restrictions</li>
                        <li style={styles.listItem}>Verifying ingredient freshness and quality</li>
                    </ul>
                    <p style={styles.paragraph}>
                        Cook AI is not responsible for any allergic reactions, foodborne illness, or health issues resulting from recipes generated by our service.
                    </p>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>6. Intellectual Property</h2>
                    <p style={styles.paragraph}>
                        The Cook AI application, including its design, features, and underlying technology, is owned by Cook AI and protected by intellectual property laws. AI-generated recipes are provided for your personal use. You may:
                    </p>
                    <ul style={styles.list}>
                        <li style={styles.listItem}>Use recipes for personal, non-commercial cooking</li>
                        <li style={styles.listItem}>Share recipes with friends and family</li>
                        <li style={styles.listItem}>Modify recipes to suit your preferences</li>
                    </ul>
                    <p style={styles.paragraph}>
                        You may not republish, redistribute, or commercially exploit recipes generated by Cook AI without permission.
                    </p>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>7. Limitation of Liability</h2>
                    <p style={styles.paragraph}>
                        Cook AI provides the service "as is" without warranties of any kind. We are not liable for:
                    </p>
                    <ul style={styles.list}>
                        <li style={styles.listItem}>Accuracy or reliability of AI-generated recipes</li>
                        <li style={styles.listItem}>Food safety issues or allergic reactions</li>
                        <li style={styles.listItem}>Cooking failures or unsatisfactory results</li>
                        <li style={styles.listItem}>Damages resulting from use of our service</li>
                        <li style={styles.listItem}>Service interruptions or technical issues</li>
                    </ul>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>8. Service Modifications</h2>
                    <p style={styles.paragraph}>
                        We reserve the right to modify, suspend, or discontinue Cook AI at any time without notice. We may also update these Terms of Use periodically. Continued use of the service after changes constitutes acceptance of the updated terms.
                    </p>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>9. Prohibited Uses</h2>
                    <p style={styles.paragraph}>
                        You may not use Cook AI to:
                    </p>
                    <ul style={styles.list}>
                        <li style={styles.listItem}>Generate recipes for harmful or dangerous purposes</li>
                        <li style={styles.listItem}>Attempt to reverse engineer or manipulate our AI system</li>
                        <li style={styles.listItem}>Scrape or extract data from our service</li>
                        <li style={styles.listItem}>Violate any applicable laws or regulations</li>
                        <li style={styles.listItem}>Interfere with other users' access to the service</li>
                    </ul>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>10. Termination</h2>
                    <p style={styles.paragraph}>
                        We reserve the right to terminate or suspend your access to Cook AI at any time, without notice, for any reason, including violation of these Terms of Use.
                    </p>
                </div>

                <div style={styles.section}>
                    <h2 style={styles.sectionTitle}>11. Governing Law</h2>
                    <p style={styles.paragraph}>
                        These Terms of Use are governed by and construed in accordance with applicable laws. Any disputes arising from these terms or use of Cook AI shall be resolved through appropriate legal channels.
                    </p>
                </div>

                <div style={styles.contactBox}>
                    <h2 style={styles.contactTitle}>Contact Us</h2>
                    <p style={styles.contactText}>
                        If you have any questions about these Terms of Use, please contact us at:
                    </p>
                    <p style={styles.contactText}>
                        By using Cook AI, you acknowledge that you have read and understood these Terms of Use and agree to be bound by them. Happy cooking! 👨‍🍳
                    </p>
                </div>
            </div>
        </div>
    );
};

export default TermsOfUse;